# Generated by Django 4.2.5 on 2024-05-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande_stagiaire',
            name='id_admin',
        ),
        migrations.AddField(
            model_name='demande_stagiaire',
            name='id_utilisateur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GESTION.utilisateur'),
            preserve_default=False,
        ),
    ]
