# Generated by Django 4.2.5 on 2024-05-07 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='date_joined',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='contratclients',
            old_name='date_joined',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='contratemployes',
            old_name='date_joined',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='demande_stagiaire',
            old_name='date_joined',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='document_important',
            old_name='date_joined',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='employes',
            old_name='date_joined',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='formations',
            old_name='date_joined',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='date_joined',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='stagiaires',
            old_name='date_joined',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='date_joined',
            new_name='date_add',
        ),
        migrations.AddField(
            model_name='administrateur',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
