# Generated by Django 4.2.5 on 2024-05-07 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0009_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrateur_g',
            options={},
        ),
        migrations.AlterModelManagers(
            name='administrateur_g',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='administrateur_g',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='administrateur_g',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='administrateur_g',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='administrateur_g',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='administrateur_g',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='administrateur_g',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='administrateur_g',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='administrateur_g',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='administrateur_g',
            name='password',
        ),
        migrations.RemoveField(
            model_name='administrateur_g',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='administrateur_g',
            name='username',
        ),
        migrations.AlterField(
            model_name='clients',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GESTION.administrateur_g'),
        ),
        migrations.AlterField(
            model_name='document_important',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GESTION.administrateur_g'),
        ),
        migrations.AlterField(
            model_name='employes',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GESTION.administrateur_g'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GESTION.administrateur_g'),
        ),
        migrations.AlterField(
            model_name='stagiaires',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GESTION.administrateur_g'),
        ),
    ]
