# Generated by Django 4.2.5 on 2024-05-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur_g',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='GESTION/static/img'),
        ),
        migrations.AlterField(
            model_name='administrateur_g',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='GESTION/static/document'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='photo_profil',
            field=models.ImageField(blank=True, default='none', null=True, upload_to='GESTION/static/img'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='piece_identite',
            field=models.FileField(blank=True, default='none', null=True, upload_to='GESTION/static/document'),
        ),
        migrations.AlterField(
            model_name='contratclients',
            name='lettre_commande',
            field=models.FileField(blank=True, null=True, upload_to='GESTION/static/document'),
        ),
        migrations.AlterField(
            model_name='contratemployes',
            name='lettre_commande',
            field=models.FileField(blank=True, null=True, upload_to='GESTION/static/document'),
        ),
        migrations.AlterField(
            model_name='demande_stagiaire',
            name='lettre_stage',
            field=models.FileField(blank=True, null=True, upload_to='GESTION/static/document'),
        ),
        migrations.AlterField(
            model_name='document_important',
            name='piece_document',
            field=models.FileField(blank=True, null=True, upload_to='GESTION/static/document'),
        ),
        migrations.AlterField(
            model_name='employes',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='GESTION/static/img'),
        ),
        migrations.AlterField(
            model_name='employes',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='GESTION/static/document'),
        ),
    ]
