# Generated by Django 4.2.5 on 2024-05-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0013_alter_administrateur_g_photo_profil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='nom_categories',
            field=models.CharField(max_length=20),
        ),
    ]
