# Generated by Django 4.2.5 on 2024-05-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0015_alter_administrateur_g_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='code_NIF',
            field=models.CharField(default='none', max_length=35, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='nom',
            field=models.CharField(default='none', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='nom_entreprise',
            field=models.CharField(default='none', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='prenom',
            field=models.CharField(default='none', max_length=30, null=True),
        ),
    ]
