# Generated by Django 4.2.5 on 2024-05-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0016_alter_clients_code_nif_alter_clients_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratclients',
            name='code_contrat',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contratclients',
            name='nom_contrat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contratemployes',
            name='code_contrat',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contratemployes',
            name='nom_contrat',
            field=models.CharField(max_length=200),
        ),
    ]
