# Generated by Django 4.2.5 on 2024-05-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0017_alter_contratclients_code_contrat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_stagiaire',
            name='message',
            field=models.TextField(default='none'),
        ),
    ]
