# Generated by Django 4.2.5 on 2024-05-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0018_alter_demande_stagiaire_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_stagiaire',
            name='message',
            field=models.TextField(default='Pas de Reponse'),
        ),
        migrations.AlterField(
            model_name='stagiaires',
            name='id_formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GESTION.formations'),
        ),
    ]
