# Generated by Django 4.2.5 on 2024-05-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0019_alter_demande_stagiaire_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('audience', models.DateField()),
                ('validation', models.CharField(default='En attente', max_length=20)),
                ('message', models.TextField(default='Pas de Reponse')),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GESTION.utilisateur')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
