# Generated by Django 4.2.5 on 2024-07-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0020_demande_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='CNI',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
    ]
