# Generated by Django 4.2.5 on 2024-07-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0021_alter_clients_cni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
