# Generated by Django 4.2.5 on 2024-07-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0022_alter_clients_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande_stagiaire',
            name='motif_stage',
        ),
        migrations.RemoveField(
            model_name='stagiaires',
            name='id_formation',
        ),
        migrations.AddField(
            model_name='demande_client',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande_stagiaire',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formations',
            name='centre',
            field=models.CharField(default='Kigobe', max_length=100),
        ),
        migrations.AddField(
            model_name='formations',
            name='domaine',
            field=models.CharField(default='Informatique', max_length=100),
        ),
        migrations.AddField(
            model_name='formations',
            name='payer',
            field=models.CharField(default='gratuit', max_length=35),
        ),
        migrations.AddField(
            model_name='stagiaires',
            name='nom_formation',
            field=models.CharField(default='PHP', max_length=20),
        ),
        migrations.AlterField(
            model_name='demande_client',
            name='audience',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demande_stagiaire',
            name='lettre_stage',
            field=models.FileField(blank=True, default='Aucun Fichier a été Envoie', null=True, upload_to='GESTION/static/document'),
        ),
        migrations.AlterField(
            model_name='stagiaires',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaires',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('type_stage', models.CharField(choices=[('academique', 'Stage académique'), ('professionnel', 'Stage professionnel')], max_length=20)),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GESTION.utilisateur')),
            ],
        ),
    ]
