# Generated by Django 4.2.5 on 2024-07-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GESTION', '0023_remove_demande_stagiaire_motif_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande_stagiaire',
            name='lettre_stage',
        ),
        migrations.AddField(
            model_name='stage',
            name='lettre_stage',
            field=models.FileField(blank=True, default='Aucun Fichier a été Envoie', null=True, upload_to='GESTION/static/document'),
        ),
    ]
