from django import views
from django.urls import path,include
from .views import *
#from account.views import login_user
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',index,name="index"),
    path('employes/',employes,name="employes"),
    path('employes/voir',employesv,name="employesv"),
    path('employes/ajouter',employesadd,name="employesadd"),
    path('employes/ajouter/add',employesad,name="employesa"),
    path('employes/visualiser/<int:id>',emplv,name="emplv"),
    path('employes/editer/<int:id>',emple,name="emple"),
    path('employes/delete/<int:id>',empld,name="empld"),
    path('clients/',clients,name="clients"),
    path('clients/ajouter',clientsadd,name="clientsadd"),
    path('clients/ajouter/add',clientsad,name="clientsad"),
    path('clients/visualiser/<int:id>',clientv,name="clientv"),
    path('clients/editer/<int:id>',cliente,name="cliente"),
    path('clients/delete/<int:id>',clientd,name="clientd"),
    path('stagiaires/',stagiaires,name="stagiaires"),
    path('stagaires/ajouter',stagiairesadd,name="stagiairesadd"),
    path('stagaires/ajouter/add',stagiairesad,name="stagiairesad"),
    path('archives/',archivres,name="archivres"),
    path('archives/ajouter',projet,name="projet"),
    path('archives/projet/editer/<int:id>',projete,name="projete"),
    path('archives/projet/delete/<int:id>',projetd,name="projetd"),
    path('archives/ajouter/add',projetadd,name="projetadd"),
    path('archives/salaires/',salaire,name="salaire"),
    path('archives/salaires/ajouter',sj,name="sajouter"),
    path('archives/salaires/editer/<int:id>',se,name="se"),
    path('archives/salaires/delete/<int:id>',sd,name="sd"),
    path('comptes/',comptes,name="comptes"),
    path('comptes/visualiser/<int:id>',visualiserc,name="visualiserc"),
    path('comptes/editer/<int:id>',editerc,name="editerc"),
    path('formations/',formations,name="formations"),
    path('formations/ajouter',formationsadd,name="formationsadd"),
    path('formations/ajouter/add',formationsad,name="formationsad"),
    path('formations/editer/<int:id>',formate,name="formate"),
    path('formations/delete/<int:id>',formad,name="formade"),
    path('archives/documents',documents,name="documents"),
    path('archives/documents/ajouter',document,name="documentsadd"),
    path('archives/documents/ajouter/add',documentsadd,name="document"),
    path('archives/documents/editer/<int:id>',doc,name="doce"),
    path('archives/contrat/clients',contratclients,name="contratclients"),
    path('archives/contrat/clients/ajouter',contratclientsadd,name="contratclientsadd"),
    path('archives/contrat/clients/ajouter/add',contratclientsad,name="contratclient"),
    path('archives/contrat/clients/editer/<int:id>',contrats,name="contrats"),
    path('archives/contrat/employes',contratemployes,name="contratemployes"),
    path('archives/contrat/employes/ajouter',contratemployesadd,name="contratemployesadd"),
    path('archives/contrat/employes/ajouter/add',contratemployesad,name="contratemploye"),
    path('archives/contrat/employes/editer/<int:id>',contrate,name="contrate"),
    path('demandes/',demandes,name="demandes"),
    path('demandes/stagiaires',demandest,name="demandest"),
    path('demandes/stagiaires/accepter/<int:id>',accepterst,name="accepterst"),
    path('demandes/stagiaires/refuser/<int:id>',refuserst,name="refuserst"),
    path('demandes/clients',demandecl,name="demandecl"),
    path('demandes/clients/accepter/<int:id>',acceptercl,name="acceptercl"),
    path('demandes/clients/refuser/<int:id>',refusercl,name="refusercl"),
    path('demandes/stages',demandesa,name="demandesa"),
    path('demandes/stages/accepter/<int:id>',acceptersa,name="acceptersa"),
    path('demandes/stages/refuser/<int:id>',refusersa,name="refusersa"),
    path('stages/',stage,name="stage"),
    path('login/',login,name="login"),
    path('logout/',logout,name="logout"),
    #path('SITE/visualiser',home_view,name="home"),   
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)